use super::{Action, ResultKind, SearchResult};
use nucleo_matcher::pattern::{CaseMatching, Normalization, Pattern};
use nucleo_matcher::{Config, Matcher, Utf32String};

/// (emoji glyph, name, extra search keywords)
struct Entry(&'static str, &'static str, &'static str);

static EMOJIS: &[Entry] = &[
    Entry("😀", "grinning face", "smile happy face"),
    Entry("😃", "grinning face with big eyes", "smile happy"),
    Entry("😄", "grinning face with smiling eyes", "smile happy laugh"),
    Entry("😁", "beaming face with smiling eyes", "smile happy grin"),
    Entry("😆", "grinning squinting face", "laugh lol haha"),
    Entry("😅", "grinning face with sweat", "laugh nervous phew"),
    Entry("🤣", "rolling on the floor laughing", "rofl lol funny"),
    Entry("😂", "face with tears of joy", "lol laugh cry funny"),
    Entry("🙂", "slightly smiling face", "smile happy"),
    Entry("🙃", "upside-down face", "silly sarcasm"),
    Entry("😉", "winking face", "wink flirt"),
    Entry("😊", "smiling face with smiling eyes", "happy blush"),
    Entry("😇", "smiling face with halo", "angel innocent"),
    Entry("🥰", "smiling face with hearts", "love crush adore"),
    Entry("😍", "heart eyes", "love crush adore"),
    Entry("🤩", "star struck", "amazed wow excited"),
    Entry("😘", "face blowing a kiss", "kiss love"),
    Entry("😗", "kissing face", "kiss"),
    Entry("😋", "face savoring food", "yum tasty delicious"),
    Entry("😛", "face with tongue", "tongue playful"),
    Entry("😜", "winking face with tongue", "tongue silly"),
    Entry("🤪", "zany face", "crazy silly wild"),
    Entry("🤑", "money mouth face", "money rich"),
    Entry("🤗", "hugging face", "hug"),
    Entry("🤭", "face with hand over mouth", "oops giggle"),
    Entry("🤫", "shushing face", "quiet secret"),
    Entry("🤔", "thinking face", "think hmm"),
    Entry("🤐", "zipper mouth face", "quiet secret silent"),
    Entry("🤨", "face with raised eyebrow", "suspicious skeptical"),
    Entry("😐", "neutral face", "meh"),
    Entry("😑", "expressionless face", "meh blank"),
    Entry("😶", "face without mouth", "silent"),
    Entry("😏", "smirking face", "smirk"),
    Entry("😒", "unamused face", "annoyed meh"),
    Entry("🙄", "face with rolling eyes", "eyeroll annoyed"),
    Entry("😬", "grimacing face", "awkward yikes"),
    Entry("🤥", "lying face", "lie pinocchio"),
    Entry("😌", "relieved face", "relief calm"),
    Entry("😔", "pensive face", "sad disappointed"),
    Entry("😪", "sleepy face", "tired sleep"),
    Entry("🤤", "drooling face", "hungry drool"),
    Entry("😴", "sleeping face", "sleep zzz tired"),
    Entry("😷", "face with medical mask", "sick mask covid"),
    Entry("🤒", "face with thermometer", "sick fever"),
    Entry("🤕", "face with head bandage", "hurt injured"),
    Entry("🤢", "nauseated face", "sick gross"),
    Entry("🤮", "vomiting face", "sick gross throw up"),
    Entry("🥵", "hot face", "heat sweating"),
    Entry("🥶", "cold face", "freezing"),
    Entry("🥴", "woozy face", "dizzy drunk"),
    Entry("😵", "dizzy face", "confused"),
    Entry("🤯", "exploding head", "mind blown shocked"),
    Entry("🤠", "cowboy hat face", "cowboy yeehaw"),
    Entry("🥳", "partying face", "party celebrate birthday"),
    Entry("😎", "smiling face with sunglasses", "cool sunglasses"),
    Entry("🤓", "nerd face", "nerd geek glasses"),
    Entry("🧐", "face with monocle", "fancy curious"),
    Entry("😕", "confused face", "confused"),
    Entry("😟", "worried face", "worried concerned"),
    Entry("🙁", "slightly frowning face", "sad frown"),
    Entry("😮", "face with open mouth", "surprised wow"),
    Entry("😯", "hushed face", "surprised quiet"),
    Entry("😲", "astonished face", "shocked surprised"),
    Entry("😳", "flushed face", "embarrassed blush"),
    Entry("🥺", "pleading face", "puppy eyes please cute"),
    Entry("😦", "frowning face with open mouth", "sad shocked"),
    Entry("😧", "anguished face", "pain shocked"),
    Entry("😨", "fearful face", "scared afraid"),
    Entry("😰", "anxious face with sweat", "nervous worried"),
    Entry("😥", "sad but relieved face", "sad relief"),
    Entry("😢", "crying face", "sad tear cry"),
    Entry("😭", "loudly crying face", "sad cry bawling"),
    Entry("😱", "face screaming in fear", "scared shock omg"),
    Entry("😖", "confounded face", "frustrated"),
    Entry("😣", "persevering face", "struggling"),
    Entry("😞", "disappointed face", "sad"),
    Entry("😓", "downcast face with sweat", "tired sweat"),
    Entry("😩", "weary face", "tired exhausted"),
    Entry("😫", "tired face", "exhausted"),
    Entry("🥱", "yawning face", "tired bored"),
    Entry("😤", "face with steam from nose", "angry triumph"),
    Entry("😡", "enraged face", "angry mad rage"),
    Entry("😠", "angry face", "mad annoyed"),
    Entry("🤬", "face with symbols on mouth", "swearing angry curse"),
    Entry("😈", "smiling face with horns", "devil evil mischief"),
    Entry("👿", "angry face with horns", "devil angry"),
    Entry("💀", "skull", "dead skeleton"),
    Entry("☠️", "skull and crossbones", "dead danger poison"),
    Entry("💩", "pile of poo", "poop funny crap"),
    Entry("🤡", "clown face", "clown joke"),
    Entry("👹", "ogre", "monster"),
    Entry("👻", "ghost", "spooky halloween"),
    Entry("👽", "alien", "ufo space"),
    Entry("🤖", "robot", "ai bot"),
    Entry("😺", "grinning cat", "cat happy"),
    Entry("😻", "heart eyes cat", "cat love"),
    Entry("😹", "cat with tears of joy", "cat laugh"),
    Entry("👋", "waving hand", "hello bye wave"),
    Entry("🤚", "raised back of hand", "hand stop"),
    Entry("🖐️", "hand with fingers splayed", "hand stop high five"),
    Entry("✋", "raised hand", "stop high five"),
    Entry("🖖", "vulcan salute", "spock star trek"),
    Entry("👌", "ok hand", "ok perfect"),
    Entry("🤌", "pinched fingers", "italian gesture"),
    Entry("🤏", "pinching hand", "small tiny"),
    Entry("✌️", "victory hand", "peace"),
    Entry("🤞", "crossed fingers", "luck hope"),
    Entry("🤟", "love-you gesture", "love rock"),
    Entry("🤘", "sign of the horns", "rock metal"),
    Entry("🤙", "call me hand", "call you phone"),
    Entry("👈", "backhand index pointing left", "point left"),
    Entry("👉", "backhand index pointing right", "point right"),
    Entry("👆", "backhand index pointing up", "point up"),
    Entry("👇", "backhand index pointing down", "point down"),
    Entry("☝️", "index pointing up", "point up"),
    Entry("👍", "thumbs up", "yes good like approve"),
    Entry("👎", "thumbs down", "no bad dislike"),
    Entry("✊", "raised fist", "fist power"),
    Entry("👊", "oncoming fist", "punch fist bump"),
    Entry("🤛", "left-facing fist", "fist bump"),
    Entry("🤜", "right-facing fist", "fist bump"),
    Entry("👏", "clapping hands", "clap applause bravo"),
    Entry("🙌", "raising hands", "celebrate yay praise"),
    Entry("👐", "open hands", "hug open"),
    Entry("🤲", "palms up together", "pray cupped hands"),
    Entry("🤝", "handshake", "deal agreement"),
    Entry("🙏", "folded hands", "please thanks pray"),
    Entry("✍️", "writing hand", "write"),
    Entry("💪", "flexed biceps", "strong muscle gym"),
    Entry("🦾", "mechanical arm", "robot strong"),
    Entry("🧠", "brain", "smart think idea"),
    Entry("👀", "eyes", "look watching"),
    Entry("👁️", "eye", "look"),
    Entry("👅", "tongue", "taste"),
    Entry("👄", "mouth", "lips"),
    Entry("❤️", "red heart", "love heart"),
    Entry("🧡", "orange heart", "love heart"),
    Entry("💛", "yellow heart", "love heart"),
    Entry("💚", "green heart", "love heart"),
    Entry("💙", "blue heart", "love heart"),
    Entry("💜", "purple heart", "love heart"),
    Entry("🖤", "black heart", "love heart dark"),
    Entry("🤍", "white heart", "love heart"),
    Entry("🤎", "brown heart", "love heart"),
    Entry("💔", "broken heart", "heartbreak sad"),
    Entry("❣️", "heart exclamation", "love"),
    Entry("💕", "two hearts", "love"),
    Entry("💞", "revolving hearts", "love"),
    Entry("💓", "beating heart", "love heartbeat"),
    Entry("💗", "growing heart", "love"),
    Entry("💖", "sparkling heart", "love"),
    Entry("💘", "heart with arrow", "love cupid"),
    Entry("💝", "heart with ribbon", "love gift"),
    Entry("💯", "hundred points", "100 perfect score"),
    Entry("💢", "anger symbol", "angry mad"),
    Entry("💥", "collision", "boom explosion"),
    Entry("💫", "dizzy", "star"),
    Entry("💦", "sweat droplets", "splash water"),
    Entry("💨", "dashing away", "fast wind run"),
    Entry("🕳️", "hole", "hole"),
    Entry("💣", "bomb", "explosive"),
    Entry("🔥", "fire", "lit flame hot"),
    Entry("⭐", "star", "favorite"),
    Entry("🌟", "glowing star", "sparkle shine"),
    Entry("✨", "sparkles", "magic shiny new"),
    Entry("⚡", "high voltage", "lightning bolt zap"),
    Entry("☀️", "sun", "sunny weather"),
    Entry("🌙", "crescent moon", "night moon"),
    Entry("☁️", "cloud", "weather cloudy"),
    Entry("🌧️", "cloud with rain", "rain weather"),
    Entry("❄️", "snowflake", "snow cold winter"),
    Entry("🌈", "rainbow", "pride colorful"),
    Entry("🎉", "party popper", "celebrate party congrats"),
    Entry("🎊", "confetti ball", "celebrate party"),
    Entry("🎁", "wrapped gift", "present birthday gift"),
    Entry("🎂", "birthday cake", "birthday cake party"),
    Entry("🏆", "trophy", "win award champion"),
    Entry("🥇", "1st place medal", "gold winner first"),
    Entry("⚽", "soccer ball", "football sports"),
    Entry("🏀", "basketball", "sports"),
    Entry("🎮", "video game controller", "gaming play"),
    Entry("🎵", "musical note", "music song"),
    Entry("🎶", "musical notes", "music song"),
    Entry("🎤", "microphone", "sing karaoke music"),
    Entry("🎧", "headphone", "music listen"),
    Entry("📱", "mobile phone", "phone cell"),
    Entry("💻", "laptop", "computer pc"),
    Entry("🖥️", "desktop computer", "computer pc"),
    Entry("⌨️", "keyboard", "type computer"),
    Entry("🖱️", "computer mouse", "computer"),
    Entry("💾", "floppy disk", "save disk"),
    Entry("📷", "camera", "photo picture"),
    Entry("🔋", "battery", "power charge"),
    Entry("💡", "light bulb", "idea bright"),
    Entry("🔍", "magnifying glass tilted left", "search find"),
    Entry("🔒", "locked", "lock secure private"),
    Entry("🔓", "unlocked", "open unlock"),
    Entry("🔑", "key", "unlock access"),
    Entry("📌", "pushpin", "pin location"),
    Entry("📍", "round pushpin", "location pin map"),
    Entry("📅", "calendar", "date schedule"),
    Entry("⏰", "alarm clock", "time wake"),
    Entry("⏳", "hourglass not done", "time waiting loading"),
    Entry("✅", "check mark button", "done yes correct"),
    Entry("❌", "cross mark", "no wrong cancel"),
    Entry("❓", "red question mark", "question what"),
    Entry("❗", "red exclamation mark", "warning important"),
    Entry("⚠️", "warning", "caution alert"),
    Entry("🚀", "rocket", "launch space fast"),
    Entry("✈️", "airplane", "travel flight"),
    Entry("🚗", "automobile", "car drive"),
    Entry("🚕", "taxi", "car cab"),
    Entry("🚲", "bicycle", "bike cycling"),
    Entry("🏠", "house", "home"),
    Entry("🏢", "office building", "work building"),
    Entry("🌍", "globe showing europe-africa", "world earth global"),
    Entry("🍕", "pizza", "food"),
    Entry("🍔", "hamburger", "food burger"),
    Entry("🍟", "french fries", "food fries"),
    Entry("🌮", "taco", "food mexican"),
    Entry("🍣", "sushi", "food japanese"),
    Entry("🍩", "doughnut", "food donut sweet"),
    Entry("🍰", "shortcake", "food cake dessert"),
    Entry("☕", "hot beverage", "coffee tea drink"),
    Entry("🍺", "beer mug", "drink beer"),
    Entry("🍷", "wine glass", "drink wine"),
    Entry("🥳", "party face", "celebrate"),
    Entry("🐶", "dog face", "dog puppy pet"),
    Entry("🐱", "cat face", "cat kitten pet"),
    Entry("🐭", "mouse face", "mouse"),
    Entry("🐻", "bear", "bear"),
    Entry("🦁", "lion", "lion"),
    Entry("🐸", "frog", "frog"),
    Entry("🐢", "turtle", "turtle slow"),
    Entry("🦋", "butterfly", "butterfly"),
    Entry("🌸", "cherry blossom", "flower spring"),
    Entry("🌹", "rose", "flower love"),
    Entry("🌻", "sunflower", "flower"),
    Entry("🌳", "deciduous tree", "tree nature"),
];

const COPY_HINT: &str = "Enter or Ctrl+C to copy";

fn to_result(e: &Entry, score: i32) -> SearchResult {
    SearchResult {
        kind: ResultKind::Emoji,
        title: super::capitalize(e.1),
        subtitle: Some(COPY_HINT.into()),
        icon: Some(e.0.to_string()),
        action: Action::CopyToClipboard(e.0.to_string()),
        score,
    }
}

/// Search the built-in emoji set by name/keywords.
pub fn search(query: &str) -> Vec<SearchResult> {
    let q = query.trim();

    if q.is_empty() {
        // A small "frequently used" style default set.
        return EMOJIS
            .iter()
            .take(16)
            .enumerate()
            .map(|(i, e)| to_result(e, 100_000 - i as i32))
            .collect();
    }

    let mut matcher = Matcher::new(Config::DEFAULT);
    let pattern = Pattern::parse(q, CaseMatching::Ignore, Normalization::Smart);
    let mut out: Vec<SearchResult> = EMOJIS
        .iter()
        .filter_map(|e| {
            let haystack = format!("{} {}", e.1, e.2);
            let hay = Utf32String::from(haystack.as_str());
            pattern
                .score(hay.slice(..), &mut matcher)
                .map(|score| to_result(e, score as i32))
        })
        .collect();
    out.sort_by(|a, b| b.score.cmp(&a.score));
    out.truncate(20);
    out
}
